---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box

suites:
- name: default
  run_list: [
    "recipe[minitest-handler::default]",
    "recipe[selinux]"
  ]
  attributes: {}

- name: disabled_noreboot
  run_list: [
    "recipe[minitest-handler::default]",
    "recipe[selinux]"
  ]
  attributes: {
    selinux: "disabled",
    force_reboot_if_needed: "false"
  }

- name: disabled_reboot
  run_list: [
    "recipe[minitest-handler::default]",
    "recipe[selinux]"
  ]
  attributes: {
    selinux: "disabled",
    force_reboot_if_needed: "true"
  }

- name: permissive_noreboot
  run_list: [
    "recipe[minitest-handler::default]",
    "recipe[selinux]"
  ]
  attributes: {
    selinux: "permissive",
    force_reboot_if_needed: "false"
  }

- name: permissive_reboot
  run_list: [
    "recipe[minitest-handler::default]",
    "recipe[selinux]"
  ]
  attributes: {
    selinux: "permissive",
    force_reboot_if_needed: "true"
  }

- name: enforcing_noreboot
  run_list: [
    "recipe[minitest-handler::default]",
    "recipe[selinux]"
  ]
  attributes: {
    selinux: "enforcing",
    force_reboot_if_needed: "false"
  }

- name: enforcing_reboot
  run_list: [
    "recipe[minitest-handler::default]",
    "recipe[selinux]"
  ]
  attributes: {
    selinux: "enforcing",
    force_reboot_if_needed: "true"
  }
